### PR TITLE
Fixes #25: Changed app icon to not be hardcoded

### LINKED ISSUE #25: hardcoded icon for mintupload
In usr/share/applications/mintupload.desktop 
you are using an hardcoded path to the icon.
result it will not change if you are choosing an other theme and it breaks the beauty of your theme.

please change the following code 

Exec=mintupload-manager
**Icon=/usr/share/pixmaps/mintupload/icon.svg**
Terminal=false
Type=Application
Encoding=UTF-8
Categories=Application;System;Settings
StartupNotify=false
NotShowIn=KDE;

to

Exec=mintupload-manager
**Icon=mintupload**
Terminal=false
Type=Application
Encoding=UTF-8
Categories=Application;System;Settings
StartupNotify=false
NotShowIn=KDE;

### PR DESCRIPTION
**Pull request by MrTimscampi**
This should make the application's icon play nice with the user's icon theme.

I moved the icon to the parent "pixmaps" folder and renamed it to "mintupload", as recommended by the FreeDesktop specs about icons.  
I also changed both the script to generate desktop files and the already present desktop files to both fix the current state of the master branch and prevent future desktop files generation to overwrite the change and break the launcher.

### CODE REVIEW

**Comment by clefebvre** [comment]
Was this tested?

Just looking at the code, I can see two uses of icon.svg...

./usr/lib/linuxmint/mintupload/mintupload_core.py:33:ICONFILE = "/usr/share/pixmaps/mintupload/icon.svg"
./usr/lib/linuxmint/mintupload/mintupload.py:28:    os.system("notify-send \"" + _("Upload Manager") + "\" \"" + message + "\" -i /usr/share/pixmaps/mintupload/icon.svg -t " + str(timeout))

**Comment by MrTimscampi** [comment]
Unfortunately, it wasn't no (I'm not a Mint user).  
I didn't realize the icon was also referenced in the code itself.

I can fix those references in code and fire up a VM to try if it runs alright afterwards, if needed.

**Comment by MrTimscampi** [comment]
Both changes to the code should work as-is.

    ./usr/lib/linuxmint/mintupload/mintupload_core.py:33:ICONFILE = "/usr/share/pixmaps/mintupload/icon.svg"

This was used by a call to gi.Notify.Notification, which according to the documentation (Found [here](https://lazka.github.io/pgi-docs/#Notify-0.7/classes/Notification.html)) supports icon themes. (Note: I noticed I made a mistake editing it, that is corrected in the 3rd commit, sorry about that.)

    ./usr/lib/linuxmint/mintupload/mintupload.py:28: os.system("notify-send "" + _("Upload Manager") + "" "" + message + "" -i /usr/share/pixmaps/mintupload/icon.svg -t " + str(timeout))

This fires up a notification through libnotify's notify-send, which also supports icon themes (This was tested on my machine by firing up the exact same command generated by the app).

**Comment by clefebvre** [comment]
This isn't good enough... I'd normally close a PR when it's not tested.

If I merge this the manager no longer opens.

You cannot use set_icon_from_file() with an icon name...

I'll tinker a bit to see if I can fix it quickly and then either merge it or close it.

**Comment by clefebvre** [comment]
ICON_FILE should be renamed ICON_NAME
set_icon_from_file() should be set_icon_name()
dialogs should use set_logo_icon_name() directly

I get a functional app with these changes but windows fail to render the icon in Cinnamon.

Maybe appsys wants it to be provided via hicolor rather than pixmaps.

In any case, this needs to be done and tested properly.

**Pull request closed without merging**
